NOT_A_NOZOMI_DIRECTORY = 1
MANIFEST_LOAD_ERROR = 2
PROGRAM_NOT_INSTALLED = 3
ERROR_INSTALLING_FILES = 4
ERROR_ADDING_SHORTCUT = 5
INSTALL_SCRIPT_NOT_FOUND = 6
INSTALL_SCRIPT_NOT_EXECUTABLE = 7
ERROR_EXECUTING_INSTALL_SCRIPT = 8
